config/routes.rb
Rails.application.routes.draw do

  get 'sponsoredposts/show'

  get 'sponsoredposts/new'

  get 'sponsoredposts/edit'

  resources :questions

  resources :advertisements
  
  resources :topics do
    resources :posts, except: [:index]
    resources :sponsoredposts, except: [:index]
  end
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    post 'up-vote' => 'votes#up_vote', as: :up_vote
    post 'down-vote' => 'votes#down_vote', as: :down_vote
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :topics, only: [] do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:new, :create, :show]
  
  post 'users/confirm' => 'users#confirm'
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :labels, only: [:show]

  #get 'welcome/index'
  root 'welcome#index'
  #get 'welcome/about'
  get 'about' => 'welcome#about'
  #get 'welcome/contact'
  get 'contact' => 'welcome#contact'
  #get 'welcome/faq'
  get 'faq' => 'welcome#faq'
  
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new] do
        resources :posts, only: [:update, :destroy]
      end
      post '/topics/:topic_id/posts/create' => 'posts#create'
      resources :posts, only: [:index, :show]
      resources :comments, only: [:index, :show]
    end
  end

end

app/models/sponsoredpost.rb
class Sponsoredpost < ActiveRecord::Base
    belongs_to :topic
end

app/controllers/sponsoredposts_controller.rb
class SponsoredpostsController < ApplicationController
  def show
    @spost = Sponsoredpost.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @spost = Sponsoredpost.new
  end
  
  def create
    @spost = Sponsoredpost.new
    @spost.title = params[:sponsoredpost][:title]
    @spost.body = params[:sponsoredpost][:body]
    @spost.price = params[:sponsoredpost][:price]
    @topic = Topic.find(params[:topic_id])
    @spost.topic = @topic
    
    if @spost.save
      flash[:notice] = "Sponsored post was saved."
      redirect_to [@topic, @spost]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @spost = Sponsoredpost.find(params[:id])
  end
  
  def update
     @spost = Sponsoredpost.find(params[:id])
     @spost.title = params[:sponsoredpost][:title]
     @spost.body = params[:sponsoredpost][:body]
     @spost.price = params[:sponsoredpost][:price]
  
     if @spost.save
       flash[:notice] = "Sponsored post was updated."
       redirect_to [@spost.topic, @spost]
     else
       flash.now[:alert] = "There was an error saving the post. Please try again."
       render :edit
     end
  end
  
  def destroy
     @spost = Sponsoredpost.find(params[:id])
 
     if @spost.destroy
       flash[:notice] = "\"#{@spost.title}\" was deleted successfully."
       redirect_to @spost.topic
     else
       flash.now[:alert] = "There was an error deleting the post."
       render :show
     end
  end
end

app/helpers/sponsoredposts_helper.rb
module SponsoredpostsHelper
end

app/views/sponsoredposts/edit.html.erb
<h1>Edit Sponsored Post</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for sponsored posts</p>
        <ul>
            <li>No rhyming allowed.</li>
            <li>Don't use the letter "C".</li>
            <li>The incessant use of hashtags will get you banned.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= form_for [@spost.topic, @spost] do |f| %>
        <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control', placeholder: "Enter sponsored post title" %>
        </div>
        <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter sponsored post body" %>
        </div>
        <div class="form-group">
            <%= f.label :price %>
            <%= f.number_field :price %>
        </div>
        <div class="form-group">
            <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
        <% end %>
    </div>
</div>

app/views/sponsoredposts/new.html.erb
<h1>New Sponsored Post</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for sponsored posts</p>
        <ul>
            <li>No rhyming allowed.</li>
            <li>Don't use the letter "C".</li>
            <li>The incessant use of hashtags will get you banned.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= form_for [@topic, @spost] do |f| %>
        <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control', placeholder: "Enter sponsored post title" %>
        </div>
        <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter sponsored post body" %>
        </div>
        <div class="form-group">
            <%= f.label :price %>
            <%= f.number_field :price %>
        </div>
        <div class="form-group">
            <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
        <% end %>
    </div>
</div>

app/views/sponsoredposts/show.html.erb
<h1><%= @spost.title %></h1>

<div class="row">
    <div class="col=md-8">
        <p><%= @spost.body %></p>
    </div>
    <div class="col-md-4">
        <%= link_to "Edit", edit_topic_sponsoredpost_path(@spost.topic, @spost), class: 'btn btn-success' %>
        <%= link_to "Delete Sponsored Post", [@spost.topic, @spost], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this sponsored post?'} %>
    </div>
</div>