config/routes.rb
Rails.application.routes.draw do

  get 'sponsoredposts/show'

  get 'sponsoredposts/new'

  get 'sponsoredposts/edit'

  resources :questions

  resources :advertisements
  
  resources :topics do
    resources :posts, except: [:index]
    resources :sponsoredposts, except: [:index]
  end
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    post 'up-vote' => 'votes#up_vote', as: :up_vote
    post 'down-vote' => 'votes#down_vote', as: :down_vote
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :topics, only: [] do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:new, :create, :show]
  
  post 'users/confirm' => 'users#confirm'
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :labels, only: [:show]

  #get 'welcome/index'
  root 'welcome#index'
  #get 'welcome/about'
  get 'about' => 'welcome#about'
  #get 'welcome/contact'
  get 'contact' => 'welcome#contact'
  #get 'welcome/faq'
  get 'faq' => 'welcome#faq'
  
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new] do
        resources :posts, only: [:update, :destroy]
      end
      post '/topics/:topic_id/posts/create' => 'posts#create'
      resources :posts, only: [:index, :show]
      resources :comments, only: [:index, :show]
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :topic
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :labelings, as: :labelable
    has_many :labels, through: :labelings
    has_many :votes, dependent: :destroy
    has_many :favorites, dependent: :destroy
    
    default_scope { order('rank DESC') }
    scope :ordered_by_title, -> { order('title') }
    scope :ordered_by_reverse_created_at, -> { order('created_at') }
    scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }
    
    validates :title, length: { minimum: 5 }, presence: true
    validates :body, length: { minimum: 20 }, presence: true
    validates :topic, presence: true
    validates :user, presence: true
    
    after_create :create_vote
    after_create :create_favorite
    
    def up_votes
        votes.where(value: 1).count
    end
    def down_votes
        votes.where(value: -1).count
    end
    def points
        votes.sum(:value)
    end
    
    def update_rank
        age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
        new_rank = points + age_in_days
        update_attribute(:rank, new_rank)
    end
    
    private ######################
    def create_vote
        user.votes.create(post: self, value: 1)
    end
    def create_favorite
        user.favorites.create(post: self)
        FavoriteMailer.new_post(user, self).deliver_now
    end
    
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::BaseController
    
    before_action :authenticate_user, except: [:index, :show]
    before_action :authorize_user, except: [:index, :show]
    
    def index
        posts = Post.all
        render json: posts, status: 200
    end
    
    def show
        post = Post.find(params[:id])
        comments = post.comments
        render json: {
            the_post: post,
            the_comments: comments
        }, status: 200
    end
    
    def update
        post = Post.find(params[:id])
        if post.update_attributes(post_params)
            render json: post, status: 200
        else
            render json: {error: "Post updated failed", status: 400}, status: 400
        end
    end
    
    def create
        post = Post.new(post_params)
        if post.valid?
            post.save!
            render json: post, status: 201
        else
            p post.errors
            render json: {error: "Post is invalid. #{post.errors}", status: 400}, status: 400
        end
    end
    
    def destroy
        post = Post.find(params[:id])
        if post.destroy
            render json: {message: "Post destroyed", status: 200}, status: 200
        else
            render json: {error: "Post destroy failed", status: 400}, status: 400
        end
    end
    
    private
    
    def post_params
        params.require(:post).permit(:title, :body, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
# index action no longer needed due to nesting
#   def index
#     @posts = Post.all
#     # optional SPAM filter:
#     # @posts.each do |post|
#     #   if (post.id == 1) || (post.id % 5 == 1)
#     #     post.title = "SPAM"
#     #   end
#     # end
#   end

  before_action :require_sign_in, except: :show
  before_action :authorize_update, except: [:show, :new, :create]
  before_action :authorize_user, except: [:show, :new, :create, :edit, :update]

  def show
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def create
   @topic = Topic.find(params[:topic_id])
   @post = @topic.posts.build(post_params)
   @post.user = current_user
  
   if @post.save
     flash[:notice] = "Post was saved."
     @post.labels = Label.update_labels(params[:post][:labels])
     redirect_to [@topic, @post]
   else
     flash.now[:alert] = "There was an error saving the post. Please try again."
     render :new
   end
  end
  
  def update
     @post = Post.find(params[:id])
     @post.assign_attributes(post_params)
  
     if @post.save
       flash[:notice] = "Post was updated."
       @post.labels = Label.update_labels(params[:post][:labels])
       redirect_to [@post.topic, @post]
     else
       flash.now[:alert] = "There was an error saving the post. Please try again."
       render :edit
     end
  end
  def destroy
     @post = Post.find(params[:id])
 
     if @post.destroy
       flash[:notice] = "\"#{@post.title}\" was deleted successfully."
       redirect_to @post.topic
     else
       flash.now[:alert] = "There was an error deleting the post."
       render :show
     end
  end
  
  private #################################
  def post_params
      params.require(:post).permit(:title, :body)
  end
  def authorize_update
      post = Post.find(params[:id])
      unless current_user == post.user || (current_user.moderator? || current_user.admin?)
        flash[:alert] = "You must be a moderator or administrator to do this action."
        redirect_to [post.topic, post]
      end
  end
  def authorize_user
      post = Post.find(params[:id])
      unless current_user == post.user || current_user.admin?
        flash[:alert] = "You must be an administrator to do this action."
        redirect_to [post.topic, post]
      end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
    def user_can_delete?(post)
        current_user && (current_user == post.user || current_user.admin?)
    end
    def user_can_edit?(post)
        current_user && (user_can_delete?(post) || current_user.moderator?)
    end
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
    <% if post.errors.any? %>
        <div class="alert alert-danger">
            <h4><%= pluralize(post.errors.count, "error") %>.</h4>
            <ul>
                <% post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <%= form_group_tag(post.errors[:title]) do %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
    <% end %>
    <%= form_group_tag(post.errors[:body]) do %>
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
    <% end %>
    <div class="form-group">
        <%= render partial: 'labels/form', locals: {f: f, labels: @topic, labels: @post.labels} %>
    </div>
    <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<div class="media">
    <div id='post-<%= post.id %>'>
        <%= render partial: 'votes/voter', locals: {post: post} %>
    </div>
    <div class="media-body">
        <h4 class="media-heading">
            <%= link_to post.title, topic_post_path(post.topic, post) %>
            <%= render partial: "labels/list", locals: { labels: post.labels } %>
        </h4>
        <small>
            submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %><br>
            <%= post.comments.count %> Comments
        </small>
    </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
<div class="col-md-4">
 <p>Guidelines for posts</p>
 <ul>
   <li>Make sure it rhymes.</li>
   <li>Don't use the letter "A".</li>
   <li>The incessant use of hashtags will get you banned.</li>
 </ul>
</div>
<div class="col-md-8">
   <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
</div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
<div class="col-md-4">
 <p>Guidelines for posts:</p>
 <ul>
   <li>Do not post illegal or violent content.</li>
   <li>No spam & no bullying.</li>
   <li>Your post should be relevant to its Topic.</li>
   <li>Tag your post with other relevant labels to help users find it.</li>
 </ul>
</div>
<div class="col-md-8">
   <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
</div>
</div>

app/views/posts/show.html.erb
<div>
    <div id='post-<%= @post.id %>'> 
        <%= render partial: 'votes/voter', locals: {post: @post} %>
    </div>
    <h1>
        <%= @post.title %> <br>
        <small>
            submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %>
        </small>
    </h1>
</div>    
<div class="row">
    <div class="col-md-8">
        <%= render partial: "labels/list", locals: { labels: @post.labels } %>
        <br />
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-8">
        <p><%= @post.body %></p>
        <div>
            <h3>Comments</h3>
            <div class='js-comments'>
                <%= render @post.comments, base: @post %>
            </div>
        </div>
        <% if current_user %>
            <div class='new-comment'>
                <%= render 'comments/form', comment: Comment.new, base: @post %>
            </div>
        <% end %>
    </div>
    
    <div class="col-md-4">
        <% if user_can_edit?(@post) %>
            <%= link_to "Edit Post", edit_topic_post_path(@post.topic, @post), class: 'btn btn-success' %>
        <% end %>
        <% if user_can_delete?(@post) %>
            <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>
        <% end %>
    </div>
    <div class="col-md-4">
        <h3>
            <div class="vote-points">
                <%= pluralize(@post.points, 'point') %>
            </div>
            <div>
                <small>
                    <%= pluralize(@post.up_votes, 'up vote') %>,
                    <%= pluralize(@post.down_votes, 'down vote') %>
                </small>
            </div>
        </h3>
        <% if current_user %>
            <%= render partial: 'favorites/favorite', locals: { post: @post } %>
        <% end %>
    </div>
</div>